export { ReactComponent as LogoIcon } from "./icon-logo.svg"
export { ReactComponent as ArrowIcon } from "./icon-arrow-down.svg"
export { ReactComponent as MoonIcon } from "./icon-moon.svg"
export { ReactComponent as NewWindowsIcon } from "./icon-new-window.svg"
export { ReactComponent as SearchIcon } from "./icon-search.svg"